### DISCUSSION TITLE
Discussions on using jsonnet for templating STAC json

### DISCUSSION THREAD

**Discussion by schwehr** [radiantearth/stac-spec#1221] [Ideas]
Hi all,

This issue is for discussion on templating STAC json using [Jsonnet](https://jsonnet.org/).  It would also be good to hear from folks who are doing templating to go from a source-of-truth (`sot`) to a STAC catalog.

Historically, the [Earth Engine public data catalog](https://developers.google.com/earth-engine/datasets) has been driven by product yaml config files.  The yaml files are instances of a protobuf product definition that is specific to Earth Engine. Those files give most of the metadata about an asset or collection that a user needs to understand when using that item in Earth Engine.  From those files, we build that public data catalog and convert and export to a [cloud storage STAC catalog](https://storage.googleapis.com/earthengine-stac/catalog/catalog.json).  We are trying to move closer to STAC json as our sot, but have a lot of redundant information in the catalog that makes maintaining a strict STAC compliant catalog more difficult.  With the yaml, we had our own inheritance based  templating system that helped somewhat.  However, I think we can do dramatically better without adding too much complexity using a lightweight setup of jsonnet.  One excellent property of jsonnet files is that an existing STAC json file can just be renamed and `jsonnet foo.jsonnet` will generate the original `foo.json` modulo order differences in the dictionary entries (as is the case with most json writing libraries).

I've created a rough prototype to illustrate the ideas.  It has both simple and more complicated cases along with a starter library of jsonnet functions that might (or might not!) make for files that are easier to read by humans. 

https://gist.github.com/schwehr/b72a7c7dad9edc10ea9ebc987c5620f1

Features of a jsonnet sot:

- It's a superset of JSON so starting out can be fairly simple
- It's fast.  I haven't benchmarked it, but generating > 300 json files from templates was quick
- Ability to greatly reduce the size of the maintained base of info
- Easy to change things like the stac version by just changing the constant in `stac_const.libsonnet`
- Comments and hidden fields/variables are allowed and won't make it to the STAC json
- Repetitive text can be put in a constant.   Or use a function for text that needs replacement
- More than one output file can be generated from one input jsonnet file
- Field keys don't needed to be quoted and for quoted strings, you have the choice of using single or double quotes

Key things that a jsonnet template sot doesn't do

- Anything with extra jsonnet features like setting the version from a variable break the ability to directly use normal stac tooling
- jssonnet doesn't actually know anything about STAC beyond what we code in supporting libsonnet files.   Folks will likely want to stick to things like pystac and language libraries to do processing based on STAC info and do validation
- It is yet another mini language to learn
- It is likely that not many people already know jsonnet

There are lots of other ways that templating can be done.  It would be good to collect examples of things done in other languages.  I thought about writing python with pystac, but that seemed pretty heavy weight.  I might do that to generate the original STAC json and then write a small python program to do the easy conversions to make a single STAC json file into a jsonnet file .e.g. set the stac version from a library, factor out common strings for our catalog, etc.

Some inline (and cut down) examples from my demo to give folks something to start on without having to go dig through my gist:

```javascript
{
  stac_version: '1.0.0-beta.2',

  // Earth Engine human readable catalog
  ee_catalog_url:
    'https://developers.google.com/earth-engine/datasets/catalog/',

  // STAC Catalog
  catalog_base: 'https://earthengine-stac.storage.googleapis.com/catalog/',
  catalog_url: self.catalog_base + 'catalog.json',
}
```

Part of stac_lib.libsonnet:

```javascript
{
  producer_provider(name, url):
    { name: name, roles: ['producer', 'licensor'], url: url },
  host_provider(ee_catalog_url):
    { name: 'Google Earth Engine', roles: ['host'], url: ee_catalog_url },

  link(_rel, _href):: { rel: _rel, href: _href },
  doi_url(doi):: 'https://doi.org/' + doi,

  extent(xmin, ymin, xmax, ymax, start, end):: {
    spatial: { bbox: [[xmin, ymin, xmax, ymax]] },
    temporal: { interval: [[start, end]] },
  },
}
```

USGS_GAP_CONUS_2011.jsonnet:

```javascript
local stac_const = import "stac_const.libsonnet";
local stac = import "stac_lib.libsonnet";

{
  local year = 2011,
  local id = 'USGS/GAP/CONUS/' + year,
  local basename = std.strReplace(id, '/', '_'),
  local basefilename = basename + '.json',
  local self_ee_catalog_url = stac_const.ee_catalog_url + basename,
  local self_url = stac_const.catalog_base + basefilename,
  local sample_url = stac_const.sample_url(basename),

  id: id,
  stac_version: stac_const.stac_version,
  stac_extensions: [
    'scientific',
    'version'
  ],
  title: std.strReplace(id, '/', ' '),
  version: '2012',
  'gee:type': 'image',
  description: |||
    The GAP/LANDFIRE National Terrestrial Ecosystems data represents a detailed
    vegetation and land cover classification for the Conterminous U.S., Alaska,
    **SNIP**
  |||,
  links: [
    {rel: 'self', href: self_url},
    {rel: 'parent', href: stac_const.catalog_url},
    {rel: 'root', href: stac_const.catalog_url},
    {rel: 'preview', href: sample_url},
    {rel: 'license', href: self_ee_catalog_url + '#terms-of-use'},
  ],
  keywords: ['gap', 'landcover', 'landfire', 'usgs', 'vegetation'],
  providers: [
    stac.producer_provider('USGS', 'http://gapanalysis.usgs.gov/gaplandcover/'),
    stac.host_provider(self_ee_catalog_url),
  ],
  extent: stac.extent(
    -127.98, 22.79, -65.27, 52.57,
    '2011-01-01T00:00:00Z', '2012-01-01T00:00:00Z'),
  // SNIP
}
```

**Comment by alexgleith** [comment]
I don't know much about Jsonnet, but the docs are very Javascript-focussed. I think we'd need more information about how the interoperability with other languages will work.

Also, the Open Data Cube has used YAML for some time, and it gets heavy to parse many documents... JSON is so easy and interoperable, I can't see the advantages in an abstraction... (But this is my very quick take, without lots of thought!)

**Comment by schwehr** [comment]
@alexgleith, Thanks for kicking off the conversation!

Hopefully this makes it a bit more clear.  Please ask anything you can think of.  And I really want to know if I've made any incorrect assumptions.

Basically, with one extra step, jsonnet using far fewer files can build a STAC json catalog tree with repetitive stuff written only once and then pulled in by functions or variables.  e.g. if you have 4 NOAA GOES fire products that are very similar, they only differ in naming and extent parameters represented by 1 jsonnet file that gets converted by the jsonnet program into 4 STAC json files like everyone is accustomed to processing.

> I think we'd need more information about how the interoperability with other languages will work.

I think your comment says I wasn't clear in my description of what is going on.  Or at least what I'm intending to have go on.    There is no goal to alter how any other language interacts with STAC json.  The jsonnet files are **only** mean to be passed through the jsonnet program (there are two versions: one in C++ and one in go).  So any use of the jsonnet source-of-truth, requires first passing the `*.jsonnet` files through the jsonnet program.  That by default emits STAC json that is just like what you would interact with using at STAC aware library like pystac.  I don't have an intension of directly reading files that are jsonnet.

> Open Data Cube has used YAML for some time, and it gets heavy to parse many documents... JSON is so easy and interoperable, I can't see the advantages in an abstraction

I am likely missing something.  In general, it's possible for most yaml or json to be converted automatically the other.  There are a few things like comments in yaml and multiple things (between `----` breaks) that won't survive going to json.  If folks add another layer of processing, then that might not be true.  Is that not correct? https://www.json2yaml.com/ seems like a nice demonstration of moving between the two.  Using that tool, I made a quick demo of one cut down stac json and then added a couple comments on the yaml side.

json on the left, yaml on the right.  Click for a readable image.

![json-yaml-comparison](https://user-images.githubusercontent.com/389869/107588275-3b6bb100-6bb8-11eb-873f-41302717a74c.png)

`NOAA_GOES_16_FDCC.json`:

```json
{
  "stac_version": "1.0.0-beta.2",
  "stac_extensions": [
    "scientific"
  ],
  "id": "NOAA/GOES/16/FDCC",
  "title": "GOES-16 FDCC Series ABI Level 2 Fire/Hot Spot Characterization CONUS",
  "gee:type": "image_collection",
  "description": "[GOES](https://www.goes.noaa.gov) satellites are geostationary weather satellites run by NOAA.\n\nThe Fire (HSC) product contains four images: [SNIP]",
  "links": [
    {
      "rel": "self",
      "href": "https://earthengine-stac.storage.googleapis.com/catalog/NOAA_GOES_16_FDCC.json"
    },
    {
      "rel": "root",
      "href": "https://earthengine-stac.storage.googleapis.com/catalog/catalog.json"
    }
  ],
  "keywords": [
    "climate",
    "wildfire"
  ],
  "providers": [
    {
      "name": "NOAA",
      "roles": [
        "producer",
        "licensor"
      ],
      "url": "https://data.noaa.gov/da [SNIP]"
    }
  ],
  "extent": {
    "spatial": {
      "bbox": [
        [
          -152.11,
          14,
          -49.18,
          56.77
        ]
      ]
    },
    "temporal": {
      "interval": [
        [
          "2017-05-24T00:00:00Z",
          null
        ]
      ]
    }
  },
  "properties": {
    "gsd": 2000,
    "eo:bands": [
      {
        "name": "Area",
        "description": "Fire area",
        "gee:unit": "m^2",
        "gee:scale": 60.98,
        "gee:offset": 4000
      },
      {
        "name": "Mask",
        "description": "Fire mask categories.  Pixel values in [SNIP]",
        "gee:classes": [
          {
            "value": 10,
            "color": "red",
            "description": "Processed fire"
          },
          {
            "value": 35,
            "color": "darkblue",
            "description": "Low probability fire, filtered"
          }
        ]
      }
    ]
  },
  "sci:citation": "Early characterization of the active fire  [SNIP]",
  "sci:publications": [
    {
      "citation": "Schmit, T., Griffith, P., et al, (2016), A closer look [SNIP]",
      "doi": "10.1175/BAMS"
    }
  ],
  "summaries": {
    "Area": {
      "min": 0,
      "max": 16723,
      "gee:estimated_range": true
    }
  }
}
```

`NOAA_GOES_16_FDCC.yaml`
```yaml
# Some comments here before the document starts
---
# This STAC yaml (which isn't really a thing) is cut down from the original
# Earth Engine NOAA_GOES_16_FDCC.json
stac_version: 1.0.0-beta.2
stac_extensions:
- scientific
id: NOAA/GOES/16/FDCC
title: GOES-16 FDCC Series ABI Level 2 Fire/Hot Spot Characterization CONUS
gee:type: image_collection
description: |-
  [GOES](https://www.goes.noaa.gov) satellites are geostationary weather satellites run by NOAA.

  The Fire (HSC) product contains four images: [SNIP]
links:
- rel: self
  href: https://earthengine-stac.storage.googleapis.com/catalog/NOAA_GOES_16_FDCC.json
- rel: root
  href: https://earthengine-stac.storage.googleapis.com/catalog/catalog.json
keywords:
- climate
- wildfire
providers:
- name: NOAA
  roles:
  - producer
  - licensor
  url: https://data.noaa.gov/da [SNIP]
extent:
  spatial:
    bbox:
    - - -152.11
      - 14
      - -49.18
      - 56.77
  temporal:
    interval:
    - - '2017-05-24T00:00:00Z'
      -
properties:
  gsd: 2000
  eo:bands:
  - name: Area
    description: Fire area
    gee:unit: m^2
    gee:scale: 60.98
    gee:offset: 4000
  - name: Mask
    description: Fire mask categories.  Pixel values in [SNIP]
    gee:classes:
    - value: 10
      color: red
      description: Processed fire
    - value: 35
      color: darkblue
      description: Low probability fire, filtered
sci:citation: Early characterization of the active fire  [SNIP]
sci:publications:
- citation: Schmit, T., Griffith, P., et al, (2016), A closer look [SNIP]
  doi: 10.1175/BAMS
summaries:
  Area:
    min: 0
    max: 16723
    gee:estimated_range: true
```

A similar `NOAA_GOES_FDC.jsonnet`.  This doesn't exactly match since I'm making examples independently as I go.  Also, this produces 4 catalog entries for 4 different GOES fire products.  (beware slightly wonky syntax highlighting)

```javascript
local stac_const = import "stac_const.libsonnet";
local stac = import "stac_lib.libsonnet";

// Probably want a stac_goes.libsonnet here.

// sat is 16 or 17
// product is 'fdcc' or 'fdcf' (fdc for fire/hotspt; c for CONUS or f for full-disk)
local goes_fdc_template(sat, product) = {
  // Left out some local functions and hidden values here.

  id: goes_id(sat, product),  // <-- This is a function that makes things like "NOAA/GOES/16/FDCC"
  'gee:type': 'image_collection',
  stac_version: stac_const.stac_version,
  stac_extensions: ['scientific'],
  title: 'GOES-' + sat + ' ' + product + ' Series ABI Level 2 Fire/Hot Spot',
  description: |||
    [GOES](https://www.goes.noaa.gov) satellites are geostationary weather
    satellites run by NOAA.
    [SNIP]
    [README](https://www.ncdc.noaa.gov/data-access/satellite-data/goes-r-series-satellites#FDC)
    NOAA provides the following scripts for suggested categories, color
    maps, and visualizations:
    - [GOES-16-17_FireDetection.js](https://github.com/google/earthengine-community/blob/master/datasets/scripts/GOES-16-17_FireDetection.js)
    - [GOES-16-17_FireReclassification.js](https://github.com/google/earthengine-community/blob/master/datasets/scripts/GOES-16-17_FireReclassification.js)
  |||,
  // TODO(schwehr): Can we use https://spdx.org/licenses/CC0-1.0.html for GOES?
  license: 'proprietary',
  links: [
    {rel: 'self', href: self_url},
    {rel: 'parent', href: stac_const.catalog_url},
    {rel: 'root', href: stac_const.catalog_url},
    {rel: 'preview', href: sample_url},
    {rel: 'license', href: self_ee_catalog_url + '#terms-of-use'},
    {rel: 'source', href: gcs_path},
    {rel: 'cite-as', href: stac.doi_url(primary_doi)}
  ],

  local this_sat = sat_info[std.toString(sat)],
  keywords: fdc_keywords + [
    'goes-' + sat,
    this_sat['letter'],
    this_sat['region'],
  ],
  providers: [
    stac.producer_provider('NOAA', noaa_fdc_url),
    stac.host_provider(self_ee_catalog_url),
  ],
  extent: extents[product + '_' + std.toString(sat)],
  properties: {
    gsd: 2000.0,
    'eo:bands': [
      {
        name: 'Area',
        description: 'Fire area',
        'gee:unit': 'm^2',
        'gee:scale': 60.98,
        'gee:offset': 4000.0
      },
      {
        name: 'Mask',
        description: |||
          Fire mask categories.  Pixel values in the fire mask image identify a
          fire category and diagnostic information associated with algorithm
          [SNIP]
	|||,
        'gee:classes': [
          stac.class_entry(10, 'red', 'Processed fire'),
          // [SNIP]
          stac.class_entry(35, 'darkblue', 'Low probability fire, filtered'),
        ]
      },
      // SNIP
    ],
  },
  'sci:citation': 'Early characterization of the active [SNIP]',
  'sci:publications': [
    {
      citation: 'Schmit, T., Griffith, P., et al, (2016), A [SNIP]',
      doi: '10.1175/BAMS'
    }
  ],
  summaries: {
    Area: stac.stats_obj(0, 16723, true),
    Temp: stac.stats_obj(0, 32642, true),
    Power: stac.stats_obj(0, 200000, false),
    DQF: stac.stats_obj(0, 5, false),
  },
};

// Generate the 4 json files.
{
  ['NOAA_GOES_' + sat + '_' + product + '.json']: goes_fdc_template(sat, product)
  for sat in [16, 17]
  for product in ['FDCC', 'FDCF']
}
```
